# Generated by Django 4.1.13 on 2024-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0002_userdata_is_active_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('city', 'city'), ('beach', 'beach'), ('arctic', 'arctic'), ('mountains', 'mountains'), ('camping', 'camping'), ('new', 'new'), ('farms', 'farms'), ('botes', 'botes')], max_length=50, null=True),
        ),
    ]
